// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzmyrpgjymixdbjskmcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6bXlycGdqeW1peGRianNrbWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjI4MTgsImV4cCI6MjA2NTQ5ODgxOH0.l0ePK1ZA6e7Olsvqv8oCkr6nBHTs50J3Ua7fv_3SRuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);